# Project configuration for Clippy Rust code linter.
# See full lints list at:
# https://rust-lang.github.io/rust-clippy/master/index.html

standard-macro-braces = [
    { name = "assert", brace = "(" },
    { name = "assert_eq", brace = "(" },
    { name = "assert_ne", brace = "(" },
    { name = "debug_assert", brace = "(" },
    { name = "debug_assert_eq", brace = "(" },
    { name = "debug_assert_ne", brace = "(" },
    { name = "format", brace = "(" },
    { name = "format_args", brace = "(" },
    { name = "matches", brace = "(" },
    { name = "panic", brace = "(" },
    { name = "print", brace = "(" },
    { name = "println", brace = "(" },
    { name = "vec", brace = "[" },
    { name = "write", brace = "(" },
    { name = "writeln", brace = "(" },
]
